john = User.create(name: "John", email: "john@john.com", password: "password", assistant_email: "charles@charles.com")
charles = User.create(name: "Charles", email: "charles@charles.com", password: "password")
tina = User.create(name: "Tina", email: "tina@tina.com", password: "password")
stephanie = User.create(name: "Stephanie", email: "stephanie@stephanie.com", password: "password")

task1 = Task.create(name: "Approve timecards", due_date: "2020-02-20", do_date: "2020-02-19", category: "approval", size: "5", status: "active", user_id: john.id)
task2 = Task.create(name: "Email Tony", due_date: "2020-01-24", do_date: "2020-01-24", category: "email", size: "3", status: "active", user_id: john.id)
task3 = Task.create(name: "New business cards", due_date: "2020-01-30", do_date: "2020-01-25", category: "admin", size: "8", status: "active", user_id: charles.id)
task4 = Task.create(name: "Schedule time with Charles", due_date: "2020-02-20", do_date: "2020-02-19", category: "scheduling", size: "5", status: "active", user_id: tina.id)
task5 = Task.create(name: "Fill out doodle poll", due_date: "2020-01-24", do_date: "2020-01-24", category: "admin", size: "3", status: "active", user_id: tina.id)
task6 = Task.create(name: "Prepare slide deck for weekly meeting", due_date: "2020-01-30", do_date: "2020-01-25", category: "deliverable", size: "13", status: "active", user_id: tina.id)
task7 = Task.create(name: "Who should be invited to the event?", due_date: "2020-02-20", do_date: "2020-02-19", category: "decision", size: "2", status: "active", user_id: john.id)
task8 = Task.create(name: "Update to website", due_date: "2020-01-24", do_date: "2020-01-24", category: "fyi", size: "3", status: "active", user_id: stephanie.id)
task9 = Task.create(name: "Book flights", due_date: "2020-01-30", do_date: "2020-01-25", category: "travel", size: "5", status: "active", user_id: stephanie.id)

note1 = Note.create(content: "Check that holidays are entered correctly", task_id: task1.id, user_id: john.id)
note2 = Note.create(content: "He had questions about what was submitted last week", task_id: task2.id, user_id: john.id)
note3 = Note.create(content: "Charles to tee up draft", task_id: task2.id, user_id: john.id)
note4 = Note.create(content: "Finalize title and desired phone number", task_id: task3.id, user_id: charles.id)
note5 = Note.create(content: "Checking up on your status for the next report", task_id: task4.id, user_id: tina.id)
note6 = Note.create(content: "Meet early next week?", task_id: task4.id, user_id: tina.id)

ref1 = Reference.create(title: "Charge codes", user_id: john.id, description: "Here is a list of charge codes you often use")
ref2 = Reference.create(title: "Scheduling preferences", user_id: john.id, description: "These are John's scheduling preferences")
ref3 = Reference.create(title: "Key contacts",  user_id: john.id, description: "These are your primary contacts")
ref4 = Reference.create(title: "Bodies of work", user_id: tina.id, description: "Different teams and workstreams")
ref5 = Reference.create(title: "Point People", user_id: tina.id, description: "Important Support Staff")
